### ISSUE TITLE
A README.md would be nice

### ISSUE THREAD

**Issue by kfl** [flamingoen/qspin#1]
It would be great with a `README.md` file with build instructions.

For macOS (10.10) I've had success with the following to get a working Qt5 installation from homebrew:

```
brew install qt5
brew link --force qt5
```

But be warned that this will conflict with Qt4 which is the current default in homebrew for some reason.

**Comment by flamingoen** [comment]
I have added a README with some instructions on how to install on different OS, including this part with installing qt5 on MAC.
